#! /bin/bash


if [[ ! $(which pip) ]]; then
	python -m ensurepip
fi

if [[ -f /etc/issue ]]; then
	if [[ $(cat /etc/issue) == 'Ubuntu 16.04.4 LTS \n \l' ]]; then
		sudo apt-get install python-software-properties -y
		sudo apt-add-repository ppa:neovim-ppa/stable -y
		sudo apt-get update -y
		sudo apt-get install neovim -y
		pip install neovim
	fi
fi 
